# Site settings
name: "Ben Kulbertis"
email: ben@kulbertis.org
description: "Full Stack Web Developer and Technology Enthusiast"
location: "Salt Lake City, Utah, USA"
baseurl: ""
url: "http://benkly.kulbertis.org"

# Build settings
markdown: rdiscount
permalink: /:year/:month/:title
highlighter: pygments